apiVersion: apps/v1

kind: Deployment

metadata:
  name: redis-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: multiapp-redis
          image: redis:latest
          resources:
            requests:
              memory: "600Mi"
              cpu: "150m"
            limits:
              memory: "500Mi"
              cpu: "100m"
          ports:
            - containerPort: 6379