apiVersion: apps/v1

kind: Deployment

metadata:
  name: worker-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 0
         maxUnavailable: 1
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: multiapp-worker
          image: home1docker1/multi-worker
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "605Mi"
              cpu: "155m"
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: '6379'