apiVersion: apps/v1

kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: multiapp-client
          image: stephengrider/multi-client
          resources:
            requests:
              memory: "600Mi"
              cpu: "150m"
            limits:
              memory: "605Mi"
              cpu: "155m"
          ports:
            - containerPort: 3000