apiVersion: apps/v1

kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      component: client
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 3
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: multiapp-client
          image: home1docker1/multi-client
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "605Mi"
              cpu: "155m"
          ports:
            - containerPort: 3000