apiVersion: apps/v1

kind: Deployment

metadata:
  name: redis-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 3
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: multiapp-redis
          image: redis:latest
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "605Mi"
              cpu: "155m"
          ports:
            - containerPort: 6379